export const CONSTANTS = {
  TOKEN: 'TOKEN',
  USER_BANK_DATA: ' USER_BANK_DATA',
  USER_DATA: 'USER_DATA',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  ADMIN_ISACCEPTED: 'ADMIN_ISACCEPTED',
  AUTH_KEY: 'AUTH_KEY',
};
